class Idiom {
  final String idiom;
  final String meaning;

  const Idiom({required this.idiom, required this.meaning});
}

class IdiomsList {
  static final List<Idiom> idiomList = [
    Idiom(idiom: 'Bump into', meaning: 'Tình cờ gặp nhau, gặp nhau bất ngờ'),
    Idiom(idiom: 'Actions	speak	louder	than	words', meaning: 'Một số lượng rất nhỏ so với số lượng cần thiết hoặc dự kiến'),
    Idiom(idiom: 'Work flat out', meaning: 'Làm việc cật lực'),
    Idiom(idiom: 'After	the	watershed', meaning: 'Một số lượng rất nhỏ so với số lượng cần thiết hoặc dự kiến'),
    Idiom(idiom: 'The in-thing', meaning: 'Hợp mốt'),
    Idiom(idiom: 'Make a fuss over', meaning: 'Cằn nhằn, cãi cọ, phàn nàn với ai về điều gì'),
    Idiom(idiom: 'Run of the mill', meaning: 'Tầm thường, không có gì đặc biệt'),
    Idiom(idiom: 'Far-fetched', meaning: 'gượng gạo, không tự nhiên, cường điệu'),
    Idiom(idiom: 'An ace up your sleeve', meaning: 'Vũ khí bí mật, quân át chủ bài, con bài bí mật, quân bài tủ, bảo bối lận lưng'),
    Idiom(idiom: 'A hot potato', meaning: 'Một sự việc hoặc chủ đề gây nhiều tranh cãi và khó khăn để giải quyết'),
    Idiom(idiom: 'Get a kick out of (something)', meaning: 'Nhận được thú vui/giải trí từ ai/cái gì; tìm thấy niềm vui thích từ ai/cái gì'),
    Idiom(idiom: 'Bent out of shape', meaning: 'Nổi điên, vô cùng tức giận'),
    Idiom(idiom: 'Give (lend) somebody a hand', meaning: 'Giúp đỡ ai đó làm gì đó'),
    Idiom(idiom: 'Sit on the fence', meaning: 'Không nghiêng về bên nào trong một cuộc tranh luận'),
    Idiom(idiom: 'A piece of cake', meaning: 'Một việc gì đó rất dễ thực hiện, tương tự cụm từ "dễ như ăn kẹo" mà người Việt hay dùng'),
    Idiom(idiom: 'Hit the books', meaning: 'Nghiên cứu, học bài để chuẩn bị cho một kỳ thi'),
    Idiom(idiom: 'A mile a minute', meaning: 'Rất nhanh'),
    Idiom(idiom: 'Learn the ropes', meaning: 'Học những điều cơ bản nhất của một chuyên môn nào đó'),
    Idiom(idiom: '(Go) back to the drawing board', meaning: 'Làm lại từ đầu'),
    Idiom(idiom: 'Go the extra mile', meaning: 'Vô cùng cố gắng'),
    Idiom(idiom: "Touch base", meaning: 'kết nối, liên lạc, nói chuyện lại, thường là sau một khoảng thời gian không liên lạc'),
    Idiom(idiom: 'Up-to-the-minute', meaning: 'Rất hiện đại, rất hợp mốt, giờ chót, rất kịp thời'),
    Idiom(idiom: 'On the go', meaning: 'Bận rộn'),
    Idiom(idiom: 'Up in the air', meaning: 'Diễn tả điều gì đó vẫn còn bỏ ngỏ, chưa được quyết định, chưa được giải quyết'),
    Idiom(idiom: 'Get off the ground', meaning: 'Bắt đầu thực hiện kế hoạch/ vấn đề nào đó sau khi được bàn bạc kỹ lưỡng'),
    Idiom(idiom: 'In high spirits', meaning: 'Vui vẻ, phấn chấn'),
    Idiom(idiom: "Keep one's chin up", meaning: 'Không được nản chí! Không được thất vọng!'),
    Idiom(idiom: 'Read my/your/his mind', meaning: 'Đoán suy nghĩ của người khác'),
    Idiom(idiom: 'Get the ball rolling', meaning: 'Bắt đầu hành động'),
    Idiom(idiom: 'By the book', meaning: 'Chấp hành quy định một cách nghiêm túc, đầy đủ'),
    Idiom(idiom: 'Pass with flying colors', meaning: 'Vượt qua kì thi với điểm số cao'),
    Idiom(idiom: '(as) easy as pie', meaning: 'Dễ ợt'),
    Idiom(idiom: 'Under the weather', meaning: 'Ốm'),
    Idiom(idiom: "Fingers-crossed = keep one's fingers crossed", meaning: 'chúc ai đó may mắn'),
    Idiom(idiom: 'Learn by heart', meaning: 'Học thuộc lòng'),
    Idiom(idiom: 'Show your hand', meaning: 'Tiết lộ ý định/kế hoạch của mình, nhất là từ trước đến nay vẫn đang giữ bí mật'),
    Idiom(idiom: 'A blessing in disguise', meaning: 'trong cái rủi có cái may'),
    Idiom(idiom: 'Be in the same boat', meaning: 'Cùng chung cảnh ngộ'),
    Idiom(idiom: 'Beating around the bush', meaning: 'Vòng vo tam quốc'),
    Idiom(idiom: 'Rack one’s brain', meaning: 'Suy nghĩ rất lâu, rất nhiều cho một vấn đề nào đó'),
    Idiom(idiom: 'A breath of fresh air', meaning: 'Điều gì đó mới mẻ'),
    Idiom(idiom: 'On cloud nine', meaning: 'Cực kỳ sung sướng, hạnh phúc như ở trên mây'),
    Idiom(idiom: 'Keep an eye on', meaning: 'để mắt tới'),
    Idiom(idiom: 'Keep your nose to the grindstone', meaning: 'hiểu rõ, quen thuộc'),
    Idiom(idiom: 'Leave well enough alone', meaning: 'để nguyên như vậy, không cần thay đổi nữa vì có thể sẽ trở nên tệ hơn'),
    Idiom(idiom: 'Now and then', meaning: 'thỉnh thoảng'),
    Idiom(idiom: 'A penny for your thoughts', meaning: 'Đây là một cách để hỏi người khác đang nghĩ gì'),
    Idiom(idiom: 'Against the clock', meaning: 'Cật lực, chạy đua với thời gian'),
    Idiom(idiom: 'Lend an ear', meaning: 'Lắng nghe'),
    Idiom(idiom: 'Blue	in	the	face', meaning: 'Cực kỳ sung sướng, hạnh phúc như ở trên mây'),
    Idiom(idiom: 'Cost a (small) fortune', meaning: 'đắt tiền'),
    Idiom(idiom: 'Hard feelings', meaning: 'Buồn phiền'),
    Idiom(idiom: "Hit the hay", meaning: 'Đi ngủ'),
    Idiom(idiom: 'Shop till you drop', meaning: 'mua sắm nhiều, số lượng lớn'),
    Idiom(idiom: '(come) rain or shine', meaning: 'Dù mưa hay nắng, dù có chuyện gì xảy ra'),
    Idiom(idiom: 'Be all ears', meaning: 'Lắng nghe'),
    Idiom(idiom: 'In the nick of time', meaning: 'Vừa đúng/kịp lúc'),
    Idiom(idiom: 'Fresh/clean out of something', meaning: 'hết nhẵn rồi'),
    Idiom(idiom: 'Have/get mixed feelings about something', meaning: 'Cảm xúc lẫn lộn, không chắc chắn'),
    Idiom(idiom: "Give it one's best shot", meaning: 'Cố hết sức có thể'),
    Idiom(idiom: 'In deep water', meaning: 'gặp rắc rối, gặp tình thế khó'),
    Idiom(idiom: 'Cost next to nothing', meaning: 'tốn ít tiền'),
    Idiom(idiom: 'To be up in arms about something', meaning: 'buồn và bực tức về vấn đề gì'),
    Idiom(idiom: "Put yourself in somebody's shoes", meaning: 'đặt mình vào vị trí của người khác'),
    Idiom(idiom: 'At all costs', meaning: 'bằng mọi giá'),
    Idiom(idiom: 'Explore all avenues', meaning: 'tìm mọi cách để làm gì đó'),
    Idiom(idiom: 'On the ball', meaning: 'hiểu và chủ động trong việc gì đó'),
    Idiom(idiom: 'Throw in the towel', meaning: 'từ bỏ, đầu hàng'),
    Idiom(idiom: 'Down to earth', meaning: 'thực tế, nếu chỉ tính cách nghĩa là tính cách bình dân bình thường, không ra vẻ, không đạo mạo'),
    Idiom(idiom: 'Full of beans', meaning: 'tràn đầy năng lượng'),
    Idiom(idiom: 'Get a head start', meaning:  'đi đầu, tiên phong'),
    Idiom(idiom: 'Hear on the grapevine', meaning: 'nghe loáng thoáng về vấn đề gì đó'),
    Idiom(idiom: 'Hit the nail on the head', meaning: 'đúng về việc gì đó'),
    Idiom(idiom: 'In the heat of the moment', meaning: 'Trong lúc nóng giận'),
    Idiom(idiom: 'It takes two to tango', meaning: 'nếu có một vấn đề liên quan đến hai người hay hai phe, thì cả hai cần hợp tác với nhau để giải quyết vấn đề đó'),
    Idiom(idiom: 'Get/jump on the bandwagon', meaning: 'tham gia vào một hoạt động phổ biến/ phong trào'),
    Idiom(idiom: 'Keep something at bay', meaning: 'ngăn ai/ cái gì tiếp tận'),
    Idiom(idiom: 'Kill two birds with one stone', meaning: 'một mũi tên trúng 2 đích'),
    Idiom(idiom: 'Break the ice', meaning: 'làm cho mọi người cảm thấy thoải mái hơn'),
    Idiom(idiom: 'Let sleeping dogs lie', meaning: 'không nhắc đến những chuyện không hay để mọi thứ được yên ổn'),
    Idiom(idiom: 'Let the cat out of the bag', meaning: 'vô tình tiết lộ bí mật'),
    Idiom(idiom: 'Barking up the wrong tree', meaning: 'nhầm lẫn/tìm kiếm giải pháp ở một nơi sai/chưa đúng'),
    Idiom(idiom: 'Far cry from - Very different from', meaning: 'rất khác biệt'),
    Idiom(idiom: 'Give someone the benefit of the doubt', meaning: 'quyết định nghĩ tốt về ai đó, trong khi bản thân đang có 2 hướng suy nghĩ xấu-tốt'),
    Idiom(idiom: "Pull the wool over someone's eyes", meaning: 'lừa dối/che mắt ai đó'),
    Idiom(idiom: 'See eye to eye', meaning: 'nhất trí'),
    Idiom(idiom: 'Take with a grain of salt', meaning: 'nửa tin nửa ngờ'),
    Idiom(idiom: 'Give someone a dose/taste of their own medicine', meaning: 'gậy ông đập lưng ông'),
    Idiom(idiom: 'Whole nine yards', meaning: 'tất cả mọi thứ'),
    Idiom(idiom: "Wouldn't be caught dead", meaning: 'thà chết chứ không làm, không bao giờ thích làm điều gì đó'),
    Idiom(idiom: 'At the drop of a hat', meaning: 'trong tích tắc, ngay lập tức'),
    Idiom(idiom: 'On the dot', meaning: 'đúng tại thời điểm đó'),
    Idiom(idiom: 'And then some', meaning: 'nhiều hơn thế'),
    Idiom(idiom: 'Find my feet', meaning: 'dần quen với việc gì'),
    Idiom(idiom: 'Your guess is as good as mine', meaning: 'Tôi không biết/không có ý tưởng gì'),
    Idiom(idiom: 'Before long', meaning: 'chẳng bao lâu nữa'),
    Idiom(idiom: 'Cost an arm and a leg', meaning: 'quá đắt đỏ'),
    Idiom(idiom: 'Set in their ways', meaning: 'không chịu thay đổi thói quen, suy nghĩ…'),
    Idiom(idiom: 'You can say that again', meaning: 'Điều đó đúng, tôi đồng ý với điều bạn nói'),
    Idiom(idiom: 'Burn the midnight oil', meaning: 'thức khuya, đặc biệt làm việc muộn'),
    Idiom(idiom:"That's the last straw", meaning: 'Sự kiên nhẫn đã chạm giới hạn'),
    Idiom(idiom: "Change one's mind", meaning: 'thay đổi quyết định/ý kiến'),
    Idiom(idiom: 'Speak of the devil', meaning: 'người mà chúng ta vừa nhắc tới xuất hiện'),
    Idiom(idiom: '(Right) off the top of my head', meaning: 'nói ra điều gì đó không cần suy nghĩ quá nhiều hay cần một kiến thức gì đó đặc biệt'),
    Idiom(idiom: 'Catch your/my/his eye', meaning: 'lôi cuốn sự chú ý/lưu tâm'),
    Idiom(idiom: 'Down in the dumps', meaning: 'buồn chán'),
    Idiom(idiom: 'Make a long story short', meaning: 'kể vắn tắt một câu chuyện'),
    Idiom(idiom: 'Put all your eggs in one basket', meaning: 'bỏ tất cả trứng vào một giỏ, bỏ tất cả tiền bạc và công sức vào việc gì đó'),
    Idiom(idiom: "It's not rocket science", meaning: 'Không phức tạp'),
    Idiom(idiom: 'Miss the boat', meaning: 'vuột mất cơ hội'),
    Idiom(idiom: 'Hang in there', meaning: 'Đừng bỏ cuộc'),
    Idiom(idiom: 'Once in a blue moon', meaning: 'hiếm khi'),
    Idiom(idiom: 'Cutting corners', meaning: 'đi tắt, đốt cháy giai đoạn / làm việc gì một cách nhanh nhất, thường là phớt lờ các quy tắc, luật lệ'),
    Idiom(idiom: 'Call it a day', meaning: 'Thôi làm việc'),
    Idiom(idiom: 'Over the moon', meaning: 'Cục kỳ hạnh phúc vì điều gì'),
    Idiom(idiom: 'Out of the blue', meaning: 'Nói về sự việc xảy ra đột ngột, không hề có cảnh báo hay chuẩn bị trước'),
    Idiom(idiom: 'Try my hand at something', meaning: 'thử sức làm công việc gì đấy'),
    Idiom(idiom: 'Pigs can fly', meaning: 'Ám chỉ một điều không bao giờ xảy ra'),
    Idiom(idiom: 'Off the beaten track', meaning: 'Miêu tả một nơi nào đó rất xa khu dân cư'),
    Idiom(idiom: 'Window shopping', meaning: 'Chỉ ngắm đồ chứ không mua'),  
  ];
}
