class IrregularVerb {
  final String infinitive;
  final String pastSimple;
  final String pastParticiple;
  final String meaning;

  const IrregularVerb(
      {required this.infinitive,
      required this.pastSimple,
      required this.pastParticiple,
      required this.meaning});
}

class IrregularVerbList {
  static final List<IrregularVerb> irregularList = [
    IrregularVerb(infinitive: 'abide',pastSimple:'abode/ abided',pastParticiple: 'abode/ abided',meaning: 'lưu trú, lưu lại'),
    IrregularVerb(infinitive: 'arise',pastSimple:'arose',pastParticiple: 'arisen',meaning: 'phát sinh'),
    IrregularVerb(infinitive: 'awake',pastSimple:'awoke',pastParticiple: 'awoken',meaning: 'đánh thức, thức'),
    IrregularVerb(infinitive: 'backslide',pastSimple:'backslid',pastParticiple: 'backslidden /backslid',meaning: 'tái phạm'),
    IrregularVerb(infinitive: 'be',pastSimple:'was/ were',pastParticiple: 'been',meaning: 'thì, là, bị, ở'),
    IrregularVerb(infinitive: 'bear',pastSimple:'bore',pastParticiple: 'born',meaning: 'mang, chịu đựng'),
    IrregularVerb(infinitive: 'beat',pastSimple:'beat',pastParticiple: 'beaten /beat',meaning: 'đánh, đập'),
    IrregularVerb(infinitive: 'become',pastSimple:'became',pastParticiple: 'become',meaning: 'trở nên'),
    IrregularVerb(infinitive: 'befall',pastSimple:'befell',pastParticiple: 'befallen',meaning: 'xảy đến'),
    IrregularVerb(infinitive: 'begin',pastSimple:'began',pastParticiple: 'begun',meaning: 'bắt đầu'),
    IrregularVerb(infinitive: 'behold',pastSimple:'beheld',pastParticiple: 'beheld',meaning: 'ngắm nhìn'),
    IrregularVerb(infinitive: 'bend',pastSimple:'bent',pastParticiple: 'bent',meaning: 'bẻ cong'),
    IrregularVerb(infinitive: 'beset',pastSimple:'beset',pastParticiple: 'beset',meaning: 'bao quanh'),
    IrregularVerb(infinitive: 'bespeak',pastSimple:'bespoke',pastParticiple: 'bespoken',meaning: 'chứng tỏ'),
    IrregularVerb(infinitive: 'bet',pastSimple:'bet/ betted',pastParticiple: 'bet/ betted',meaning: 'đánh cược, cá cược'),
    IrregularVerb(infinitive: 'bid',pastSimple:'bid',pastParticiple: 'bid',meaning: 'trả giá'),
    IrregularVerb(infinitive: 'bind',pastSimple:'bound',pastParticiple: 'bound',meaning: 'buộc, trói'),
    IrregularVerb(infinitive: 'bite',pastSimple:'bit',pastParticiple: 'bitten',meaning: 'cắn'),
    IrregularVerb(infinitive: 'bleed',pastSimple:'bled',pastParticiple: 'bled',meaning: 'chảy máu'),
    IrregularVerb(infinitive: 'blow',pastSimple:'blew',pastParticiple: 'blown',meaning: 'thổi'),
    IrregularVerb(infinitive: 'break',pastSimple:'broke',pastParticiple: 'broken',meaning: 'đập vỡ'),
    IrregularVerb(infinitive: 'breed',pastSimple:'bred',pastParticiple: 'bred',meaning: 'nuôi, dạy dỗ'),
    IrregularVerb(infinitive: 'bring',pastSimple:'brought',pastParticiple: 'brought',meaning: 'mang đến'),
    IrregularVerb(infinitive: 'broadcast',pastSimple:'broadcast',pastParticiple: 'broadcast',meaning: 'phát thanh'),
    IrregularVerb(infinitive: 'browbeat',pastSimple:'browbeat',pastParticiple: 'browbeaten /browbeat',meaning: 'hăm dọa'),
    IrregularVerb(infinitive: 'build',pastSimple:'built',pastParticiple: 'built',meaning: 'xây dựng'),
    IrregularVerb(infinitive: 'burn',pastSimple:'burnt/ burned',pastParticiple: 'burnt/ burned',meaning: 'đốt, cháy'),
    IrregularVerb(infinitive: 'burst',pastSimple:'burst',pastParticiple: 'burst',meaning: 'nổ tung, vỡ òa'),
    IrregularVerb(infinitive: 'bust',pastSimple:'busted /bust',pastParticiple: 'busted /bust',meaning: 'làm bể, làm vỡ'),
    IrregularVerb(infinitive: 'buy',pastSimple:'bought',pastParticiple: 'bought',meaning: 'mua'),
    IrregularVerb(infinitive: 'cast',pastSimple:'cast',pastParticiple: 'cast',meaning: 'ném, tung'),
    IrregularVerb(infinitive: 'catch',pastSimple:'caught',pastParticiple: 'caught',meaning: 'bắt, chụp'),
    IrregularVerb(infinitive: 'chide',pastSimple:'chide',pastParticiple: 'chid/ chidden /chided',meaning: 'mắng, chửi'),
    IrregularVerb(infinitive: 'choose',pastSimple:'chose',pastParticiple: 'chosen',meaning: 'chọn, lựa'),
    IrregularVerb(infinitive: 'cleave',pastSimple:'clove /cleft /cleaved',pastParticiple: 'cloven/ cleft/ cleaved',meaning: 'chẻ, tách hai'),
    IrregularVerb(infinitive: 'cleave',pastSimple:'clave',pastParticiple: 'cleaved',meaning: 'dính chặt'),
    IrregularVerb(infinitive: 'cling',pastSimple:'clung',pastParticiple: 'clung',meaning: 'bám vào, dính vào'),
    IrregularVerb(infinitive: 'clothe',pastSimple:'clothed /clad ',pastParticiple: 'clothed /clad ',meaning: 'che phủ'),
    IrregularVerb(infinitive: 'come',pastSimple:'came',pastParticiple: 'come',meaning: 'đến, đi đến'),
    IrregularVerb(infinitive: 'cost',pastSimple:'cost',pastParticiple: 'cost',meaning: 'có giá là'),
    IrregularVerb(infinitive: 'creep',pastSimple:'crept',pastParticiple: 'crept',meaning: 'bò, trườn, lẻn'),
    IrregularVerb(infinitive: 'crossbreed',pastSimple:'crossbred',pastParticiple: 'crossbred',meaning: 'cho lai giống'),
    IrregularVerb(infinitive: 'crow',pastSimple:'crew/ crewed',pastParticiple: 'crowed',meaning: 'gáy (gà)'),
    IrregularVerb(infinitive: 'cut',pastSimple:'cut',pastParticiple: 'cut',meaning: 'cắt, chặt'),
    IrregularVerb(infinitive: 'daydream',pastSimple:'daydreamed /daydreamt',pastParticiple: 'daydreamed /daydreamt',meaning: 'nghĩ vẩn vơ, mơ mộng'),
    IrregularVerb(infinitive: 'deal',pastSimple:'dealt',pastParticiple: 'dealt',meaning: 'giao thiệp'),
    IrregularVerb(infinitive: 'dig',pastSimple:'dug',pastParticiple: 'dug',meaning: 'đào'),
    IrregularVerb(infinitive: 'disprove',pastSimple:'disproved',pastParticiple: 'disproved/ disproven ',meaning: 'bác bỏ'),
    IrregularVerb(infinitive: 'dive',pastSimple:'dove/dived',pastParticiple: 'dived',meaning: 'lặn, lao xuống'),
    IrregularVerb(infinitive: 'do',pastSimple:'did',pastParticiple: 'done',meaning: 'làm'),
    IrregularVerb(infinitive: 'draw',pastSimple:'drew',pastParticiple: 'drawn',meaning: 'vẽ, kéo'),
    IrregularVerb(infinitive: 'dream',pastSimple:'dreamt/ dreamed',pastParticiple: 'dreamt/ dreamed',meaning: 'mơ thấy'),
    IrregularVerb(infinitive: 'drink',pastSimple:'drank',pastParticiple: 'drunk',meaning: 'uống'),
    IrregularVerb(infinitive: 'drive',pastSimple:'drove',pastParticiple: 'driven',meaning: 'lái xe'),
    IrregularVerb(infinitive: 'dwell',pastSimple:'dwelt',pastParticiple: 'dwelt',meaning: 'trú ngụ, ở'),
    IrregularVerb(infinitive: 'eat',pastSimple:'ate',pastParticiple: 'eaten',meaning: 'ăn'),
    IrregularVerb(infinitive: 'fall',pastSimple:'fell',pastParticiple: 'fallen',meaning: 'ngã, rơi'),
    IrregularVerb(infinitive: 'feed',pastSimple:'fed',pastParticiple: 'fed',meaning: 'cho ăn, ăn, nuôi'),
    IrregularVerb(infinitive: 'feel',pastSimple:'felt',pastParticiple: 'felt',meaning: 'cảm thấy'),
    IrregularVerb(infinitive: 'fight',pastSimple:'fought',pastParticiple: 'fought',meaning: 'chiến đấu'),
    IrregularVerb(infinitive: 'find',pastSimple:'found',pastParticiple: 'found',meaning: 'tìm thấy, thấy'),
    IrregularVerb(infinitive: 'fit',pastSimple:'fitted /fit',pastParticiple: 'fitted /fit',meaning: 'làm cho vừa, làm cho hợp'),
    IrregularVerb(infinitive: 'flee',pastSimple:'fled',pastParticiple: 'fled',meaning: 'chạy trốn'),
    IrregularVerb(infinitive: 'fling',pastSimple:'flung',pastParticiple: 'flung',meaning: 'tung, quăng'),
    IrregularVerb(infinitive: 'fly',pastSimple:'flew',pastParticiple: 'flown',meaning: 'bay'),
    IrregularVerb(infinitive: 'forbear',pastSimple:'forbore',pastParticiple: 'forborn',meaning: 'nhịn'),
    IrregularVerb(infinitive: 'forbid',pastSimple:'forbade /forbad',pastParticiple: 'forbidden',meaning: 'cấm, cấm đoán'),
    IrregularVerb(infinitive: 'forecast',pastSimple:'forecast/ forecasted',pastParticiple: 'forecast/ forecasted',meaning: 'tiên đoán'),
    IrregularVerb(infinitive: 'forego (forgo)',pastSimple:'forewent',pastParticiple: 'foregone',meaning: 'bỏ, kiêng'),
    IrregularVerb(infinitive: 'foresee',pastSimple:'foresaw',pastParticiple: 'forseen',meaning: 'thấy trước'),
    IrregularVerb(infinitive: 'foretell',pastSimple:'foretold',pastParticiple: 'foretold',meaning: 'đoán trước'),
    IrregularVerb(infinitive: 'forget',pastSimple:'forgot',pastParticiple: 'forgotten',meaning: 'quên'),
    IrregularVerb(infinitive: 'forgive',pastSimple:'forgave',pastParticiple: 'forgiven',meaning: 'tha thứ'),
    IrregularVerb(infinitive: 'forsake',pastSimple:'forsook',pastParticiple: 'forsaken',meaning: 'ruồng bỏ'),
    IrregularVerb(infinitive: 'freeze',pastSimple:'froze',pastParticiple: 'frozen',meaning: '(làm) đông lại'),
    IrregularVerb(infinitive: 'frostbite',pastSimple:'frostbit',pastParticiple: 'frostbitten',meaning: 'bỏng lạnh'),
    IrregularVerb(infinitive: 'get',pastSimple:'got',pastParticiple: 'got/ gotten',meaning: 'có được'),
    IrregularVerb(infinitive: 'gild',pastSimple:'gilt/ gilded',pastParticiple: 'gilt/ gilded',meaning: 'mạ vàng'),
    IrregularVerb(infinitive: 'gird',pastSimple:'girt/ girded',pastParticiple: 'girt/ girded',meaning: 'đeo vào'),
    IrregularVerb(infinitive: 'give',pastSimple:'gave',pastParticiple: 'given',meaning: 'cho'),
    IrregularVerb(infinitive: 'go',pastSimple:'went',pastParticiple: 'gone',meaning: 'đi'),
    IrregularVerb(infinitive: 'grind',pastSimple:'ground',pastParticiple: 'ground',meaning: 'nghiền, xay'),
    IrregularVerb(infinitive: 'grow',pastSimple:'grew',pastParticiple: 'grown',meaning: 'mọc, trồng'),
    IrregularVerb(infinitive: 'hand-feed',pastSimple:'hand-fed',pastParticiple: 'hand-fed',meaning: 'cho ăn bằng tay'),
    IrregularVerb(infinitive: 'handwrite',pastSimple:'handwrote',pastParticiple: 'handwritten',meaning: 'viết tay'),
    IrregularVerb(infinitive: 'hang',pastSimple:'hung',pastParticiple: 'hung',meaning: 'móc lên, treo lên'),
    IrregularVerb(infinitive: 'have',pastSimple:'had',pastParticiple: 'had',meaning: 'có'),
    IrregularVerb(infinitive: 'hear',pastSimple:'heard',pastParticiple: 'heard',meaning: 'nghe'),
    IrregularVerb(infinitive: 'heave',pastSimple:'hove/ heaved',pastParticiple: 'hove/ heaved',meaning: 'trục lên'),
    IrregularVerb(infinitive: 'hew',pastSimple:'hewed',pastParticiple: 'hewn/ hewed',meaning: 'chặt, đốn'),
    IrregularVerb(infinitive: 'hide',pastSimple:'hid',pastParticiple: 'hidden',meaning: 'giấu, trốn, nấp'),
    IrregularVerb(infinitive: 'hit',pastSimple:'hit',pastParticiple: 'hit',meaning: 'đụng'),
    IrregularVerb(infinitive: 'hurt',pastSimple:'hurt',pastParticiple: 'hurt',meaning: 'làm đau'),
    IrregularVerb(infinitive: 'inbreed',pastSimple:'inbred',pastParticiple: 'inbred',meaning: 'lai giống cận huyết'),
    IrregularVerb(infinitive: 'inlay',pastSimple:'inlaid',pastParticiple: 'inlaid',meaning: 'cẩn, khảm'),
    IrregularVerb(infinitive: 'input',pastSimple:'input',pastParticiple: 'input',meaning: 'đưa vào'),
    IrregularVerb(infinitive: 'inset',pastSimple:'inset',pastParticiple: 'inset',meaning: 'dát, ghép'),
    IrregularVerb(infinitive: 'interbreed',pastSimple:'interbred',pastParticiple: 'interbred',meaning: 'giao phối, lai giống'),
    IrregularVerb(infinitive: 'interweave',pastSimple:'interwove/ interweaved',pastParticiple: 'interwoven/ interweaved',meaning: 'trộn lẫn, xen lẫn'),
    IrregularVerb(infinitive: 'interwind',pastSimple:'interwound',pastParticiple: 'interwound',meaning: 'cuộn vào, quấn vào'),
    //100
    IrregularVerb(infinitive: 'jerry-build',pastSimple:'jerry-built',pastParticiple: 'jerry-built',meaning: 'xây dựng cẩu thả'),
    IrregularVerb(infinitive: 'keep',pastSimple:'kept',pastParticiple: 'kept',meaning: 'giữ'),
    IrregularVerb(infinitive: 'kneel',pastSimple:'knelt/ kneeled',pastParticiple: 'knelt/ kneeled',meaning: 'quỳ'),
    IrregularVerb(infinitive: 'knit',pastSimple:'knit/ knitted',pastParticiple: 'knit/ knitted',meaning: 'đan'),
    IrregularVerb(infinitive: 'know',pastSimple:'knew',pastParticiple: 'known',meaning: 'biết, quen biết'),
    IrregularVerb(infinitive: 'lay',pastSimple:'laid',pastParticiple: 'laid',meaning: 'đặt, để'),
    IrregularVerb(infinitive: 'lead',pastSimple:'led',pastParticiple: 'led',meaning: 'dẫn dắt, lãnh đạo'),
    IrregularVerb(infinitive: 'lean',pastSimple:'leaned /leant ',pastParticiple: 'leaned /leant ',meaning: 'dựa, tựa'),
    IrregularVerb(infinitive: 'leap',pastSimple:'leapt',pastParticiple: 'leapt',meaning: 'nhảy, nhảy qua'),
    IrregularVerb(infinitive: 'learn',pastSimple:'learnt/ learned',pastParticiple: 'learnt/ learned',meaning: 'học, được biết'),
    
    IrregularVerb(infinitive: 'leave',pastSimple:'left',pastParticiple: 'left',meaning: 'ra đi, để lại'),
    IrregularVerb(infinitive: 'lend',pastSimple:'lent',pastParticiple: 'lent',meaning: 'cho mượn'),
    IrregularVerb(infinitive: 'let',pastSimple:'let',pastParticiple: 'let',meaning: 'cho phép, để cho'),
    IrregularVerb(infinitive: 'lie',pastSimple:'lay',pastParticiple: 'lain',meaning: 'nằm'),
    IrregularVerb(infinitive: 'light',pastSimple:'lit/lighted',pastParticiple: 'lit/lighted',meaning: 'thắp sáng'),
    IrregularVerb(infinitive: 'lip-read',pastSimple:'lip-read',pastParticiple: 'lip-read',meaning: 'mấp máy môi'),
    IrregularVerb(infinitive: 'lose',pastSimple:'lost',pastParticiple: 'lost',meaning: 'làm mất, mất'),
    IrregularVerb(infinitive: 'make',pastSimple:'made',pastParticiple: 'made',meaning: 'chế tạo, sản xuất'),
    IrregularVerb(infinitive: 'mean',pastSimple:'meant',pastParticiple: 'meant',meaning: 'có nghĩa là'),
    IrregularVerb(infinitive: 'meet',pastSimple:'met',pastParticiple: 'met',meaning: 'gặp mặt'),
    
    IrregularVerb(infinitive: 'miscast',pastSimple:'miscast',pastParticiple: 'miscast',meaning: 'chọn vai đóng không hợp'),
    IrregularVerb(infinitive: 'misdeal',pastSimple:'misdealt',pastParticiple: 'misdealt',meaning: 'chia lộn bài, chia bài sai'),
    IrregularVerb(infinitive: 'misdo',pastSimple:'misdid',pastParticiple: 'misdone',meaning: 'phạm lỗi'),
    IrregularVerb(infinitive: 'mishear',pastSimple:'misheard',pastParticiple: 'misheard',meaning: 'nghe nhầm'),
    IrregularVerb(infinitive: 'mislay',pastSimple:'mislaid',pastParticiple: 'mislaid',meaning: 'để lạc mất'),
    IrregularVerb(infinitive: 'mislead',pastSimple:'misled',pastParticiple: 'misled',meaning: 'làm lạc đường'),
    IrregularVerb(infinitive: 'mislearn',pastSimple:'mislearned /mislearnt',pastParticiple: 'mislearned /mislearnt',meaning: 'học nhầm'),
    IrregularVerb(infinitive: 'misread',pastSimple:'misread',pastParticiple: 'misread',meaning: 'đọc sai'),
    IrregularVerb(infinitive: 'misset',pastSimple:'misset',pastParticiple: 'misset',meaning: 'đặt sai chỗ'),
    IrregularVerb(infinitive: 'misspeak',pastSimple:'misspoke',pastParticiple: 'misspoken',meaning: 'nói sai'),

    
    IrregularVerb(infinitive: 'misspell',pastSimple:'misspelt',pastParticiple: 'misspelt',meaning: 'viết sai chính tả'),
    IrregularVerb(infinitive: 'misspend',pastSimple:'misspent',pastParticiple: 'misspent',meaning: 'tiêu phí, bỏ phí'),
    IrregularVerb(infinitive: 'mistake',pastSimple:'mistook',pastParticiple: 'mistaken',meaning: 'phạm lỗi, lầm lẫn'),
    IrregularVerb(infinitive: 'misteach',pastSimple:'mistaught',pastParticiple: 'mistaught',meaning: 'dạy sai'),
    IrregularVerb(infinitive: 'misunderstand',pastSimple:'misunderstood',pastParticiple: 'misunderstood',meaning: 'hiểu lầm'),
    IrregularVerb(infinitive: 'miswrite',pastSimple:'miswrote',pastParticiple: 'miswritten',meaning: 'viết sai'),
    IrregularVerb(infinitive: 'mow',pastSimple:'mowed',pastParticiple: 'mown/ mowed',meaning: 'cắt cỏ'),
    IrregularVerb(infinitive: 'offset',pastSimple:'offset',pastParticiple: 'offset',meaning: 'đền bù'),
    IrregularVerb(infinitive: 'outbid',pastSimple:'outbid',pastParticiple: 'outbid',meaning: 'trả hơn giá'),
    IrregularVerb(infinitive: 'outbreed',pastSimple:'outbred',pastParticiple: 'outbred',meaning: 'giao phối xa'),

    
    IrregularVerb(infinitive: 'outdo',pastSimple:'outdid',pastParticiple: 'outdone',meaning: 'làm giỏi hơn'),
    IrregularVerb(infinitive: 'outdraw',pastSimple:'outdrew',pastParticiple: 'outdraw',meaning: 'rút súng ra nhanh hơn'),
    IrregularVerb(infinitive: 'outdrink',pastSimple:'outdrank',pastParticiple: 'outdrunk',meaning: 'uống quá chén'),
    IrregularVerb(infinitive: 'outdrive',pastSimple:'outdrove',pastParticiple: 'outdriven',meaning: 'lái nhanh hơn'),
    IrregularVerb(infinitive: 'outfight',pastSimple:'outfought',pastParticiple: 'outfought',meaning: 'đánh giỏi hơn'),
    IrregularVerb(infinitive: 'outfly',pastSimple:'outflew',pastParticiple: 'outflown',meaning: 'bay cao /xa hơn'),
    IrregularVerb(infinitive: 'outgrow',pastSimple:'outgrew',pastParticiple: 'outgrown',meaning: 'lớn nhanh hơn'),
    IrregularVerb(infinitive: 'outleap',pastSimple:'outleaped /outleapt ',pastParticiple: 'outleaped /outleapt ',meaning: 'nhảy cao/xa hơn'),
    IrregularVerb(infinitive: 'outlie',pastSimple:'outlied',pastParticiple: 'outlied',meaning: 'nói dối'),
    IrregularVerb(infinitive: 'output',pastSimple:'output',pastParticiple: 'output',meaning: 'cho ra (dữ kiện)'),
    
    IrregularVerb(infinitive: 'outride',pastSimple:'outrode',pastParticiple: 'outridden',meaning: 'cưỡi ngựa giỏi hơn'),
    IrregularVerb(infinitive: 'outrun',pastSimple:'outran',pastParticiple: 'outrun',meaning: 'chạy nhanh hơn, vượt giá'),
    IrregularVerb(infinitive: 'outsell',pastSimple:'outsold',pastParticiple: 'outsold',meaning: 'bán nhanh hơn'),
    IrregularVerb(infinitive: 'outshine',pastSimple:'outshined /outshone ',pastParticiple: 'outshined /outshone ',meaning: 'sáng hơn, rạng rỡ hơn'),
    IrregularVerb(infinitive: 'outshoot',pastSimple:'outshot',pastParticiple: 'outshot',meaning: 'bắn giỏi hơn, nảy mầm, mọc'),
    IrregularVerb(infinitive: 'outsing',pastSimple:'outsang',pastParticiple: 'outsung',meaning: 'hát hay hơn'),
    IrregularVerb(infinitive: 'outsit',pastSimple:'outsat',pastParticiple: 'outsat',meaning: 'ngồi lâu hơn'),
    IrregularVerb(infinitive: 'outsleep',pastSimple:'outslept',pastParticiple: 'outslept',meaning: 'ngủ lâu/muộn hơn'),
    IrregularVerb(infinitive: 'outsmell',pastSimple:'outsmelled /outsmelt',pastParticiple: 'outsmelled /outsmelt',meaning: 'khám phá, đánh hơi, sặc mùi'),
    IrregularVerb(infinitive: 'outspeak',pastSimple:'outspoke',pastParticiple: 'outspoken ',meaning: 'nhiều /dài /to hơn'),

    IrregularVerb(infinitive: 'outspeed',pastSimple:'outsped',pastParticiple: 'outsped',meaning: 'đi/chạy nhanh hơn'),
    IrregularVerb(infinitive: 'outspend',pastSimple:'outspent',pastParticiple: 'outspent',meaning: 'tiêu tiền nhiều hơn'),
    IrregularVerb(infinitive: 'outswear',pastSimple:'outswore',pastParticiple: 'outsworn',meaning: 'nguyền rủa nhiều hơn'),
    IrregularVerb(infinitive: 'outswim',pastSimple:'outswam',pastParticiple: 'outswum',meaning: 'bơi giỏi hơn'),
    IrregularVerb(infinitive: 'outthink',pastSimple:'outthought',pastParticiple: 'outthought',meaning: 'suy nghĩ nhanh hơn'),
    IrregularVerb(infinitive: 'outthrow',pastSimple:'outthrew',pastParticiple: 'outthrown',meaning: 'ném nhanh hơn'),
    IrregularVerb(infinitive: 'outwrite',pastSimple:'outwrote',pastParticiple: 'outwritten',meaning: 'viết nhanh hơ'),
    IrregularVerb(infinitive: 'overbid',pastSimple:'overbid',pastParticiple: 'overbid',meaning: 'trả giá/bỏ thầu cao hơn'),
    IrregularVerb(infinitive: 'overbreed',pastSimple:'overbred',pastParticiple: 'overbred',meaning: 'nuôi quá nhiều'),
    IrregularVerb(infinitive: 'overbuild',pastSimple:'overbuilt',pastParticiple: 'overbuilt',meaning: 'xây quá nhiều'),

    IrregularVerb(infinitive: 'overbuy',pastSimple:'overbought',pastParticiple: 'overbought',meaning: 'mua quá nhiều'),
    IrregularVerb(infinitive: 'overcome',pastSimple:'overcame',pastParticiple: 'overcome',meaning: 'khắc phục'),
    IrregularVerb(infinitive: 'overdo',pastSimple:'overdid',pastParticiple: 'overdone',meaning: 'dùng quá mức, làm quá'),
    IrregularVerb(infinitive: 'overdraw',pastSimple:'overdrew',pastParticiple: 'overdrawn',meaning: 'rút quá số tiền, phóng đại'),
    IrregularVerb(infinitive: 'overdrink',pastSimple:'overdrank',pastParticiple: 'overdrunk',meaning: 'uống quá nhiều'),
    IrregularVerb(infinitive: 'overeat',pastSimple:'overate',pastParticiple: 'overeaten',meaning: 'ăn quá nhiều'),
    IrregularVerb(infinitive: 'overfeed',pastSimple:'overfed',pastParticiple: 'overfed',meaning: 'cho ăn quá mức'),
    IrregularVerb(infinitive: 'overfly',pastSimple:'overflew',pastParticiple: 'overflown',meaning: 'bay qua'),
    IrregularVerb(infinitive: 'overhang',pastSimple:'overhung',pastParticiple: 'overhung',meaning: 'nhô lên trên, treo lơ lửng'),
    IrregularVerb(infinitive: 'overhear',pastSimple:'overheard',pastParticiple: 'overheard',meaning: 'nghe trộm'),
    
    IrregularVerb(infinitive: 'overlay',pastSimple:'overlaid',pastParticiple: 'overlaid',meaning: 'phủ lên'),
    IrregularVerb(infinitive: 'overpay',pastSimple:'overpaid',pastParticiple: 'overpaid',meaning: 'trả quá tiền'),
    IrregularVerb(infinitive: 'override',pastSimple:'overrode',pastParticiple: 'overridden',meaning: 'lạm quyền'),
    IrregularVerb(infinitive: 'overrun',pastSimple:'overran',pastParticiple: 'overrun',meaning: 'tràn ngập'),
    IrregularVerb(infinitive: 'oversee',pastSimple:'oversaw',pastParticiple: 'overseen',meaning: 'trông nom'),
    IrregularVerb(infinitive: 'oversell',pastSimple:'oversold',pastParticiple: 'oversold',meaning: 'bán quá mức'),
    IrregularVerb(infinitive: 'oversew',pastSimple:'oversewed',pastParticiple: 'oversewn/ oversewed',meaning: 'may nối vắt'),
    IrregularVerb(infinitive: 'overshoot',pastSimple:'overshot',pastParticiple: 'overshot',meaning: 'đi quá đích'),
    IrregularVerb(infinitive: 'oversleep',pastSimple:'overslept',pastParticiple: 'overslept',meaning: 'ngủ quên'),
    IrregularVerb(infinitive: 'overspeak',pastSimple:'overspoke',pastParticiple: 'overspoken',meaning: 'Nói quá nhiều, nói lấn át'),
    
    IrregularVerb(infinitive: 'overspend',pastSimple:'overspent',pastParticiple: 'overspent',meaning: 'tiêu quá lố'),
    IrregularVerb(infinitive: 'overspill',pastSimple:'overspilled /overspilt',pastParticiple: 'overspilled /overspilt',meaning: 'đổ, làm tràn'),
    IrregularVerb(infinitive: 'overtake',pastSimple:'overtook',pastParticiple: 'overtaken',meaning: 'đuổi bắt kịp'),
    IrregularVerb(infinitive: 'overthink',pastSimple:'overthought',pastParticiple: 'overthought',meaning: 'tính trước nhiều quá'),
    IrregularVerb(infinitive: 'overthrow',pastSimple:'overthrew',pastParticiple: 'overthrown',meaning: 'lật đổ'),
    IrregularVerb(infinitive: 'overwind',pastSimple:'overwound',pastParticiple: 'overwound',meaning: 'lên dây (đồng hồ) quá chặt'),
    IrregularVerb(infinitive: 'overwrite',pastSimple:'overwrote',pastParticiple: 'overwritten',meaning: 'viết dài quá, viết đè lên'),
    IrregularVerb(infinitive: 'partake',pastSimple:'partook',pastParticiple: 'partaken',meaning: 'tham gia, dự phần'),
    IrregularVerb(infinitive: 'pay',pastSimple:'paid',pastParticiple: 'paid',meaning: 'trả (tiền)'),
    IrregularVerb(infinitive: 'plead',pastSimple:'pleaded /pled',pastParticiple: 'pleaded /pled',meaning: 'bào chữa, biện hộ'),
    
    IrregularVerb(infinitive: 'prebuild',pastSimple:'prebuilt',pastParticiple: 'prebuilt',meaning: 'làm nhà tiền chế'),
    IrregularVerb(infinitive: 'predo',pastSimple:'predid',pastParticiple: 'predone',meaning: 'làm trước'),
    IrregularVerb(infinitive: 'premake',pastSimple:'premade',pastParticiple: 'premade',meaning: 'làm trước'),
    IrregularVerb(infinitive: 'prepay',pastSimple:'prepaid',pastParticiple: 'prepaid',meaning: 'trả trước'),
    IrregularVerb(infinitive: 'presell',pastSimple:'presold',pastParticiple: 'presold',meaning: 'bán trước thời gian rao báo'),
    IrregularVerb(infinitive: 'preset',pastSimple:'preset',pastParticiple: 'preset',meaning: 'thiết lập sẵn, cài đặt sẵn'),
    IrregularVerb(infinitive: 'preshrink',pastSimple:'preshrank',pastParticiple: 'preshrunk',meaning: 'ngâm cho vải co trước khi may'),
    IrregularVerb(infinitive: 'proofread',pastSimple:'proofread',pastParticiple: 'proofread',meaning: 'Đọc bản thảo trước khi in'),
    IrregularVerb(infinitive: 'prove',pastSimple:'proved',pastParticiple: 'proven /proved',meaning: 'chứng minh'),
    IrregularVerb(infinitive: 'put',pastSimple:'put',pastParticiple: 'put',meaning: 'đặt, để'),
    IrregularVerb(infinitive: 'quick-freeze',pastSimple:'quick-froze',pastParticiple: 'quick-frozen',meaning: 'kết đông nhanh'),
    
    IrregularVerb(infinitive: 'quit',pastSimple:'quit/ quitted ',pastParticiple: 'quit/ quitted ',meaning: 'bỏ'),
    IrregularVerb(infinitive: 'read',pastSimple:'read',pastParticiple: 'read',meaning: 'đọc'),
    IrregularVerb(infinitive: 'reawake',pastSimple:'reawoke',pastParticiple: 'reawaken',meaning: 'đánh thức 1 lần nữa'),
    IrregularVerb(infinitive: 'rebid',pastSimple:'rebid',pastParticiple: 'rebid',meaning: 'trả giá, bỏ thầu'),
    IrregularVerb(infinitive: 'rebind',pastSimple:'rebound',pastParticiple: 'rebound',meaning: 'buộc lại, đóng lại'),
    IrregularVerb(infinitive: 'rebroadcast',pastSimple:'rebroadcast/ rebroadcasted',pastParticiple: 'rebroadcast/ rebroadcasted',meaning: 'cự tuyệt, khước từ'),
    IrregularVerb(infinitive: 'rebuild',pastSimple:'rebuilt',pastParticiple: 'rebuilt',meaning: 'xây dựng lại'),
    IrregularVerb(infinitive: 'recast',pastSimple:'recast',pastParticiple: 'recast',meaning: 'đúc lại'),
    IrregularVerb(infinitive: 'recut',pastSimple:'recut',pastParticiple: 'recut',meaning: 'cắt lại, băm'),
    
    IrregularVerb(infinitive: 'redeal',pastSimple:'redealt',pastParticiple: 'redealt',meaning: 'phát bài lại'),
    IrregularVerb(infinitive: 'redo',pastSimple:'redid',pastParticiple: 'redone',meaning: 'làm lại'),
    IrregularVerb(infinitive: 'redraw',pastSimple:'redrew',pastParticiple: 'redrawn',meaning: 'kéo ngược lại'),
    IrregularVerb(infinitive: 'refit',pastSimple:'refitted /refit ',pastParticiple: 'refitted /refit ',meaning: 'luồn, xỏ'),
    IrregularVerb(infinitive: 'regrind',pastSimple:'reground',pastParticiple: 'reground',meaning: 'mài sắc lại'),
    IrregularVerb(infinitive: 'regrow',pastSimple:'regrew',pastParticiple: 'regrown',meaning: 'trồng lại'),
    IrregularVerb(infinitive: 'rehang',pastSimple:'rehung',pastParticiple: 'rehung',meaning: 'treo lại'),
    IrregularVerb(infinitive: 'rehear',pastSimple:'reheard',pastParticiple: 'reheard',meaning: 'nghe trình bày lại'),
    IrregularVerb(infinitive: 'reknit',pastSimple:'reknitted /reknit',pastParticiple: 'reknitted /reknit',meaning: 'đan lại'),
    IrregularVerb(infinitive: 'relay',pastSimple:'relaid',pastParticiple: 'relaid',meaning: 'đặt lại'),

    IrregularVerb(infinitive: 'relay',pastSimple:'relayed',pastParticiple: 'relayed',meaning: 'truyền âm lại'),    
    IrregularVerb(infinitive: 'relearn',pastSimple:'relearned /relearnt',pastParticiple: 'relearned /relearnt',meaning: 'học lại'),
    IrregularVerb(infinitive: 'relight',pastSimple:'relit/ relighted',pastParticiple: 'relit/ relighted',meaning: 'thắp sáng lại'),
    IrregularVerb(infinitive: 'remake',pastSimple:'remade',pastParticiple: 'remade',meaning: 'làm lại, chế tạo lại'),
    IrregularVerb(infinitive: 'rend',pastSimple:'rent',pastParticiple: 'rent',meaning: 'toạc ra, xé'),
    IrregularVerb(infinitive: 'repay',pastSimple:'repaid',pastParticiple: 'repaid',meaning: 'hoàn tiền lại'),
    IrregularVerb(infinitive: 'reread',pastSimple:'reread',pastParticiple: 'reread',meaning: 'đọc lại'),
    IrregularVerb(infinitive: 'rerun',pastSimple:'reran',pastParticiple: 'rerun',meaning: 'chiếu lại, phát lại'),
    IrregularVerb(infinitive: 'resell',pastSimple:'resold',pastParticiple: 'resold',meaning: 'bán lại'),
    IrregularVerb(infinitive: 'resend',pastSimple:'resent',pastParticiple: 'resent',meaning: 'gửi lại'),
    
    IrregularVerb(infinitive: 'reset',pastSimple:'reset',pastParticiple: 'reset',meaning: 'đặt lại, lắp lại'),
    IrregularVerb(infinitive: 'resew',pastSimple:'resewed',pastParticiple: 'resewn/ resewed',meaning: 'may/ khâu lại'),
    IrregularVerb(infinitive: 'retake',pastSimple:'retook',pastParticiple: 'retaken',meaning: 'chiếm lại, tái chiếm'),
    IrregularVerb(infinitive: 'reteach',pastSimple:'retaught',pastParticiple: 'retaught',meaning: 'dạy lại'),
    IrregularVerb(infinitive: 'retear',pastSimple:'retore',pastParticiple: 'retorn',meaning: 'khóc lại'),
    IrregularVerb(infinitive: 'retell',pastSimple:'retold',pastParticiple: 'retold',meaning: 'kể lại'),
    IrregularVerb(infinitive: 'rethink',pastSimple:'rethought',pastParticiple: 'rethought',meaning: 'suy tính lại'),
    IrregularVerb(infinitive: 'retread',pastSimple:'retread',pastParticiple: 'retread',meaning: 'lại giẫm/ đạp lên'),
    IrregularVerb(infinitive: 'retrofit',pastSimple:'retrofitted /retrofit ',pastParticiple: 'retrofitted /retrofit ',meaning: 'trang bị thêm những bộ phận mới'),
    IrregularVerb(infinitive: 'rewake',pastSimple:'rewoke/ rewaked',pastParticiple: 'rewoke/ rewaked',meaning: 'đánh thức lại'),
    
    IrregularVerb(infinitive: 'rewear',pastSimple:'rewore',pastParticiple: 'reworn',meaning: 'mặc lại'),
    IrregularVerb(infinitive: 'reweave',pastSimple:'rewove/ reweaved',pastParticiple: 'rewoven/ reweaved',meaning: 'dệt lại'),
    IrregularVerb(infinitive: 'rewed',pastSimple:'rewed/ rewedded',pastParticiple: 'rewed/ rewedded',meaning: 'kết hôn lại'),
    IrregularVerb(infinitive: 'rewet',pastSimple:'rewet/ rewetted',pastParticiple: 'rewet/ rewetted',meaning: 'làm ướt lại'),
    IrregularVerb(infinitive: 'rewin',pastSimple:'rewon',pastParticiple: 'rewon',meaning: 'thắng lại'),
    IrregularVerb(infinitive: 'rewind',pastSimple:'rewound',pastParticiple: 'rewound',meaning: 'cuốn lại, lên dây lại'),
    IrregularVerb(infinitive: 'rewrite',pastSimple:'rewrote',pastParticiple: 'rewritten',meaning: 'viết lại'),
    IrregularVerb(infinitive: 'rid',pastSimple:'rid',pastParticiple: 'rid',meaning: 'giải thoát'),
    IrregularVerb(infinitive: 'ride',pastSimple:'rode',pastParticiple: 'ridden',meaning: 'cưỡi'),
    IrregularVerb(infinitive: 'ring',pastSimple:'rang',pastParticiple: 'rung',meaning: 'rung chuông'),
    
    IrregularVerb(infinitive: 'rise',pastSimple:'rose',pastParticiple: 'risen',meaning: 'đứng dậy, mọc'),
    IrregularVerb(infinitive: 'roughcast',pastSimple:'roughcast',pastParticiple: 'roughcast',meaning: 'tạo hình phỏng chừng'),
    IrregularVerb(infinitive: 'run',pastSimple:'ran',pastParticiple: 'run',meaning: 'chạy'),
    IrregularVerb(infinitive: 'sand-cast',pastSimple:'sand-cast',pastParticiple: 'sand-cast',meaning: 'đúc bằng khuôn cát'),
    IrregularVerb(infinitive: 'saw',pastSimple:'sawed',pastParticiple: 'sawn',meaning: 'cưa'),
    IrregularVerb(infinitive: 'say',pastSimple:'said',pastParticiple: 'said',meaning: 'nói'),
    IrregularVerb(infinitive: 'see',pastSimple:'saw',pastParticiple: 'seen',meaning: 'nhìn thấy'),
    IrregularVerb(infinitive: 'seek',pastSimple:'sought',pastParticiple: 'sought',meaning: 'tìm kiếm'),
    IrregularVerb(infinitive: 'sell',pastSimple:'sold',pastParticiple: 'sold',meaning: 'bán'),
    IrregularVerb(infinitive: 'send',pastSimple:'sent',pastParticiple: 'sent',meaning: 'gửi'),
    
    IrregularVerb(infinitive: 'set',pastSimple:'set',pastParticiple: 'set',meaning: 'đặt, thiết lập'),
    IrregularVerb(infinitive: 'sew',pastSimple:'sewed',pastParticiple: 'sewn/ sewed',meaning: 'may'),
    IrregularVerb(infinitive: 'shake',pastSimple:'shook',pastParticiple: 'shaken',meaning: 'lay, lắc'),
    IrregularVerb(infinitive: 'shave',pastSimple:'shaved',pastParticiple: 'shaved/ shaven',meaning: 'cạo (râu, mặt)'),
    IrregularVerb(infinitive: 'shear',pastSimple:'sheared',pastParticiple: 'shorn',meaning: 'xén lông (cừu)'),
    IrregularVerb(infinitive: 'shed',pastSimple:'shed',pastParticiple: 'shed',meaning: 'rơi, rụng'),
    IrregularVerb(infinitive: 'shine',pastSimple:'shone',pastParticiple: 'shone',meaning: 'chiếu sáng'),
    IrregularVerb(infinitive: 'shit',pastSimple:'shit/ shat/ shitted',pastParticiple: 'shit/ shat/ shitted',meaning: 'suộc khuộng đi đại tiện'),
    IrregularVerb(infinitive: 'shoot',pastSimple:'shot',pastParticiple: 'shot',meaning: 'bắn'),
    IrregularVerb(infinitive: 'show',pastSimple:'showed',pastParticiple: 'shown /showed',meaning: 'cho xem'),
    
    IrregularVerb(infinitive: 'shrink',pastSimple:'shrank',pastParticiple: 'shunk',meaning: 'co rút'),
    IrregularVerb(infinitive: 'shut',pastSimple:'shut',pastParticiple: 'shut',meaning: 'đóng lại'),
    IrregularVerb(infinitive: 'sight-read',pastSimple:'sight-read',pastParticiple: 'sight-read',meaning: 'chơi hoặc hát mà không cần nghiên cứu trước'),
    IrregularVerb(infinitive: 'sing',pastSimple:'sang',pastParticiple: 'sung',meaning: 'ca hát'),
    IrregularVerb(infinitive: 'sink',pastSimple:'sank',pastParticiple: 'sunk',meaning: 'chìm, lặn'),
    IrregularVerb(infinitive: 'sit',pastSimple:'sat',pastParticiple: 'sat',meaning: 'ngồi'),
    IrregularVerb(infinitive: 'slay',pastSimple:'slew',pastParticiple: 'slain',meaning: 'sát hại, giết hại'),
    IrregularVerb(infinitive: 'sleep',pastSimple:'slept',pastParticiple: 'slept',meaning: 'ngủ'),
    IrregularVerb(infinitive: 'slide',pastSimple:'slid',pastParticiple: 'slid',meaning: 'trượt, lướt'),
    IrregularVerb(infinitive: 'sling',pastSimple:'slung',pastParticiple: 'slung',meaning: 'ném mạnh'),
    
    IrregularVerb(infinitive: 'slink',pastSimple:'slunk',pastParticiple: 'slunk',meaning: 'lẻn đi'),
    IrregularVerb(infinitive: 'slit',pastSimple:'slit',pastParticiple: 'slit',meaning: 'rạch, khứa'),
    IrregularVerb(infinitive: 'smell',pastSimple:'smelt',pastParticiple: 'smelt',meaning: 'ngửi'),
    IrregularVerb(infinitive: 'smite',pastSimple:'smote',pastParticiple: 'smitten',meaning: 'đập mạnh'),
    IrregularVerb(infinitive: 'sneak',pastSimple:'sneaked /snuck',pastParticiple: 'sneaked /snuck',meaning: 'trốn, lén'),
    IrregularVerb(infinitive: 'speak',pastSimple:'spoke',pastParticiple: 'spoken',meaning: 'nói'),
    IrregularVerb(infinitive: 'speed',pastSimple:'sped/ speeded',pastParticiple: 'sped/ speeded',meaning: 'chạy vụt'),
    IrregularVerb(infinitive: 'spell',pastSimple:'spelt/ spelled',pastParticiple: 'spelt/ spelled',meaning: 'đánh vần'),
    IrregularVerb(infinitive: 'spend',pastSimple:'spent',pastParticiple: 'spent',meaning: 'tiêu xài'),

    IrregularVerb(infinitive: 'spill',pastSimple:'spilt/ spilled',pastParticiple: 'spilt/ spilled',meaning: 'tràn, đổ ra'),    
    IrregularVerb(infinitive: 'spin',pastSimple:'spun/ span',pastParticiple: 'spun' ,meaning: 'quay sợi'),
    IrregularVerb(infinitive: 'spoil',pastSimple:'spoilt/ spoiled',pastParticiple: 'spoilt/ spoiled',meaning: 'làm hỏng'),
    IrregularVerb(infinitive: 'spread',pastSimple:'spread',pastParticiple: 'spread',meaning: 'lan truyền'),
    IrregularVerb(infinitive: 'stand',pastSimple:'stood',pastParticiple: 'stood',meaning: 'đứng'),
    IrregularVerb(infinitive: 'steal',pastSimple:'stole',pastParticiple: 'stolen',meaning: 'đánh cắp'),
    IrregularVerb(infinitive: 'stick',pastSimple:'stuck',pastParticiple: 'stuck',meaning: 'ghim vào, đính'),
    IrregularVerb(infinitive: 'sting',pastSimple:'stung',pastParticiple: 'stung',meaning: 'châm, chích, đốt'),
    IrregularVerb(infinitive: 'stink',pastSimple:'stunk/ stank',pastParticiple: 'stunk',meaning: 'bốc mùi hôi'),
    IrregularVerb(infinitive: 'stride',pastSimple:'strode',pastParticiple: 'stridden',meaning: 'bước sải'),
    IrregularVerb(infinitive: 'strike',pastSimple:'struck',pastParticiple: 'struck',meaning: 'đánh đập'),
    
    IrregularVerb(infinitive: 'string',pastSimple:'strung',pastParticiple: 'strung',meaning: 'gắn dây vào'),
    IrregularVerb(infinitive: 'sunburn',pastSimple:'sunburned /sunburnt ',pastParticiple: 'sunburned /sunburnt ',meaning: 'cháy nắng'),
    IrregularVerb(infinitive: 'swear',pastSimple:'swore',pastParticiple: 'sworn',meaning: 'tuyên thệ'),
    IrregularVerb(infinitive: 'sweat',pastSimple:'sweat/ sweated',pastParticiple: 'sweat/ sweated',meaning: 'đổ mồ hôi'),
    IrregularVerb(infinitive: 'sweep',pastSimple:'swept',pastParticiple: 'swept',meaning: 'quét'),
    IrregularVerb(infinitive: 'swell',pastSimple:'swelled',pastParticiple: 'swollen /swelled',meaning: 'phồng, sưng'),
    IrregularVerb(infinitive: 'swim',pastSimple:'swam',pastParticiple: 'swum',meaning: 'bơi lội'),
    IrregularVerb(infinitive: 'swing',pastSimple:'swung',pastParticiple: 'swung',meaning: 'đong đưa'),
    IrregularVerb(infinitive: 'take',pastSimple:'took',pastParticiple: 'taken',meaning: 'cầm, lấy'),
    IrregularVerb(infinitive: 'teach',pastSimple:'taught',pastParticiple: 'taught',meaning: 'dạy, giảng dạy'),
    
    IrregularVerb(infinitive: 'tear',pastSimple:'tore',pastParticiple: 'torn',meaning: 'xé, rách'),
    IrregularVerb(infinitive: 'telecast',pastSimple:'telecast',pastParticiple: 'telecast',meaning: 'phát đi bằng truyền hình'),
    IrregularVerb(infinitive: 'tell',pastSimple:'told',pastParticiple: 'told',meaning: 'kể, bảo'),
    IrregularVerb(infinitive: 'think',pastSimple:'thought',pastParticiple: 'thought',meaning: 'suy nghĩ'),
    IrregularVerb(infinitive: 'throw',pastSimple:'threw',pastParticiple: 'thrown',meaning: 'ném, liệng'),
    IrregularVerb(infinitive: 'thrust',pastSimple:'thrust',pastParticiple: 'thrust',meaning: 'thọc, nhấn'),
    IrregularVerb(infinitive: 'tread',pastSimple:'trod',pastParticiple: 'trodden/trod',meaning: 'giẫm, đạp'),
    IrregularVerb(infinitive: 'typewrite',pastSimple:'typewrote',pastParticiple: 'typewritten',meaning: 'đánh máy'),
    IrregularVerb(infinitive: 'unbend',pastSimple:'unbent',pastParticiple: 'unbent',meaning: 'làm thẳng lại'),
    IrregularVerb(infinitive: 'unbind',pastSimple:'unbound',pastParticiple: 'unbound',meaning: 'mở, tháo ra'),
    
    IrregularVerb(infinitive: 'unclothe',pastSimple:'unclothed /unclad',pastParticiple: 'unclothed /unclad',meaning: 'cởi áo, lột trần'),
    IrregularVerb(infinitive: 'undercut',pastSimple:'undercut',pastParticiple: 'undercut',meaning: 'ra giá rẻ hơn'),
    IrregularVerb(infinitive: 'underfeed',pastSimple:'underfed',pastParticiple: 'underfed',meaning: 'cho ăn đói, thiếu ăn'),
    IrregularVerb(infinitive: 'undergo',pastSimple:'underwent',pastParticiple: 'undergone',meaning: 'kinh qua'),
    IrregularVerb(infinitive: 'underlie',pastSimple:'underlay',pastParticiple: 'underlain',meaning: 'nằm dưới'),
    IrregularVerb(infinitive: 'understand',pastSimple:'understood',pastParticiple: 'understood',meaning: 'hiểu'),
    IrregularVerb(infinitive: 'undertake',pastSimple:'undertook',pastParticiple: 'undertaken',meaning: 'đảm nhận'),
    IrregularVerb(infinitive: 'underwrite',pastSimple:'underwrote',pastParticiple: 'underwritten',meaning: 'bảo hiểm'),
    IrregularVerb(infinitive: 'undo',pastSimple:'undid',pastParticiple: 'undone',meaning: 'tháo ra'),
    IrregularVerb(infinitive: 'unfreeze',pastSimple:'unfroze',pastParticiple: 'unfrozen',meaning: 'làm tan đông'),
    
    IrregularVerb(infinitive: 'unhang',pastSimple:'unhung',pastParticiple: 'unhung',meaning: 'hạ xuống, bỏ xuống'),
    IrregularVerb(infinitive: 'unhide',pastSimple:'unhid',pastParticiple: 'unhidden',meaning: 'hiển thị, không ẩn'),
    IrregularVerb(infinitive: 'unlearn',pastSimple:'unlearned /unlearnt ',pastParticiple: 'unlearned /unlearnt ',meaning: 'gạt bỏ, quên'),
    IrregularVerb(infinitive: 'unspin',pastSimple:'unspun',pastParticiple: 'unspun',meaning: 'quay ngược'),
    IrregularVerb(infinitive: 'unwind',pastSimple:'unwound',pastParticiple: 'unwound',meaning: 'tháo ra'),
    IrregularVerb(infinitive: 'uphold',pastSimple:'upheld',pastParticiple: 'upheld',meaning: 'ủng hộ'),
    IrregularVerb(infinitive: 'upset',pastSimple:'upset',pastParticiple: 'upset',meaning: 'đánh đổ, lật đổ'),
    IrregularVerb(infinitive: 'wake',pastSimple:'woke /waked',pastParticiple: 'woken /waked',meaning: 'thức giấc'),
    IrregularVerb(infinitive: 'wear',pastSimple:'wore',pastParticiple: 'worn',meaning: 'mặc'),
    IrregularVerb(infinitive: 'wed',pastSimple:'wed/ wedded',pastParticiple: 'wed/ wedded',meaning: 'kết hôn'),
    
    IrregularVerb(infinitive: 'weep',pastSimple:'wept',pastParticiple: 'wept',meaning: 'khóc'),
    IrregularVerb(infinitive: 'wet',pastSimple:'wet/ wetted',pastParticiple: 'wet/ wetted',meaning: 'làm ướt'),
    IrregularVerb(infinitive: 'win',pastSimple:'won',pastParticiple: 'won',meaning: 'thắng, chiến thắng'),
    IrregularVerb(infinitive: 'wind',pastSimple:'wound',pastParticiple: 'wound',meaning: 'quấn'),
    IrregularVerb(infinitive: 'withdraw',pastSimple:'withdrew',pastParticiple: 'withdrawn',meaning: 'rút lui'),
    IrregularVerb(infinitive: 'withhold',pastSimple:'withheld',pastParticiple: 'withheld',meaning: 'từ khước'),
    IrregularVerb(infinitive: 'withstand',pastSimple:'withstood',pastParticiple: 'withstood',meaning: 'cầm cự'),
    IrregularVerb(infinitive: 'work',pastSimple:'worked',pastParticiple: 'worked',meaning: 'rèn, nhào nặn đất'),
    IrregularVerb(infinitive: 'wring',pastSimple:'wrung',pastParticiple: 'wrung',meaning: 'vặn, siết chặt'),
    IrregularVerb(infinitive: 'write',pastSimple:'wrote',pastParticiple: 'written',meaning: 'viết'),
  ];
}
