class SystemData {
  static Map<String, List<String>> defaultWordset = {
    'Fruits': [
      "Avocado",
      "Apple",
      "Orange",
      "Banana",
      "Grape",
      "Grapefruit",
      "Starfruit",
      "Mango",
      "Pineapple",
      "Mangosteen",
      "Mandarin",
      "Kiwi fruit",
      "Kumquat",
      "Jackfruit",
      "Durian",
      "Lemon",
      "Lime",
      "Papaya",
      "Soursop",
      "Custard-apple",
      "Plum",
      "Apricot",
      "Peach",
      "Cherry",
      "Rambutan",
      "Coconut",
      "Guava",
      "Pear",
      "Fig",
      "Dragon fruit",
      "Melon",
      "Watermelon",
      "Lychee",
      "Longan",
      "Pomegranate",
      "Berry",
      "Strawberry",
      "Passion-fruit",
      "Persimmon",
      "Tamarind",
      "Cranberry",
      "Jujube",
      "Das",
      "Green almonds",
      "Ugli fruit",
      "Citron",
      "Currant",
      "Ambarella",
      "Indian cream cobra melon",
      "Granadilla",
      "Cantaloupe",
      "Honeydew",
      "Malay apple",
      "Star apple",
      "Almond",
      "Chestnut",
      "Honeydew melon",
      "Blackberries",
      "Raisin"
    ],
    'Emotions': [
      "Amused",
      "Delighted",
      "Ecstatic",
      "Enthusiastic",
      "Excited",
      "Great",
      "Happy",
      "Intrigued",
      "Keen",
      "Nonplussed",
      "Overwhelmed",
      "Over the moon",
      "Overjoyed",
      "Positive",
      "Relaxed",
      "Seething",
      "Surprised",
      "Terrific",
      "Wonderful",
      "Angry",
      "Anxious",
      "Annoyed",
      "Appalled",
      "Apprehensive",
      "Arrogant",
      "Ashamed",
      "Bewildered",
      "Bored",
      "Confident",
      "Cheated",
      "Confused",
      "Cross",
      "Depressed",
      "Disappointed",
      "Emotional",
      "Envious",
      "Embarrassed",
      "Frightened",
      "Frustrated",
      "Furious",
      "Horrified",
      "Hurt"
    ],
    'Music': [
      "Beat",
      "Sheet",
      "Lyrics",
      "Tone",
      "Background music",
      "Metre",
      "Melody",
      "Rhythm",
      "Voice",
      "Stave",
      "Scale",
      "Bass clef",
      "Solo",
      "Treble clef",
      "Live music",
      "Chord",
      "In tune",
      "Out of tune",
      "A massive hit",
      "Orchestra",
      "Alto",
      "Tenor",
      "Bass",
      "Soprano",
      "Note"
    ],
    'Friendship': [
      "Schoolmate",
      "Pen-pal",
      "Classmate",
      "Bosom friend",
      "Roommate",
      "Close friend",
      "Soulmate",
      "Best friend",
      "Colleague",
      "Girlfriend",
      "Comrade",
      "Boyfriend",
      "Partner",
      "Companion",
      "Associate",
      "Ally",
      "Buddy"
    ],
    'Time': [],
    'Health': [
      "Health",
      "Healthy",
      "Sickness",
      "Headache",
      "Toothache",
      "Sore eyes",
      "Sore throat",
      "Cold",
      "Flu",
      "Cough",
      "Fever",
      "Fever virus",
      "Runny nose",
      "Sneeze",
      "Backache",
      "Under the weather",
      "As right as rain",
      "Splitting headache",
      "Run down",
      "Back on my feet",
      "As fit as a fiddle"
    ],
    'Seafood': [
      "Prawn",
      "Squid",
      "Cuttlefish",
      "Shrimp",
      "Lobster",
      "Oyster",
      "Crab",
      "Sentinel crab",
      "Cockle",
      "Blood cockle",
      "Scallop",
      "Sea urchin",
      "Sea cucumber",
      "Jellyfish",
      "Sweet snail",
      "Horn snail",
      "Octopus",
      "Clam",
      "Abalone",
      "Mussel"
    ],
  };
}
